# Generated by Django 4.2.6 on 2023-10-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cart_coupons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='coupons',
            new_name='coupon',
        ),
    ]
