# Generated by Django 4.2.6 on 2023-10-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='id_expired',
            new_name='is_expired',
        ),
    ]
